#!/bin/bash
PROJECT_ROOT=`pwd`
export APP_ROOT=$PROJECT_ROOT
mkdir -p log
touch log/webserver.log

# Webserver will deliver fixture files from port 8000
cd $PROJECT_ROOT/tests/fixtures
python -m SimpleHTTPServer > $PROJECT_ROOT/log/webserver.log 2>&1 &
WEB_PID=$!

cd $PROJECT_ROOT
#Compile the current state, on success run tests.
script/rebar clean compile skip_deps=true && script/test-runner $*
TEST_EXIT=$?
kill $WEB_PID
exit $TEST_EXIT
